school_project/school_website/school_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('schoolapp.urls')),
    path('schoolapp1/',include('schoolapp1.urls'))
]

school_project/school_website/schoolapp/urls.py
from . import views
from django.urls import path, include

app_name='schoolapp'

urlpatterns = [
    path('',views.home,name='home'),
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('detail',views.detail,name='detail')

]

school_project/school_website/schoolapp1/urls.py
from . import views
from django.urls import path

app_name='schoolapp1'

urlpatterns = [

    path('user_form/', views.user_form, name='user_form'),
    path('success/', views.success, name='success'),

]

school_project/school_website/schoolapp/models.py
from django.db import models

# Create your models here.

school_project/school_website/schoolapp1/models.py
from django.db import models

class Department(models.Model):
    name = models.CharField(max_length=100)


class Course(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

school_project/school_website/schoolapp1/forms.py
from django import forms
from .models import Department, Course

class UserForm(forms.Form):
    name = forms.CharField(max_length=100)
    dob = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    age = forms.IntegerField(widget=forms.NumberInput(attrs={'id': 'age-field'}))
    gender = forms.ChoiceField(choices=[('M', 'Male'), ('F', 'Female')])
    phone_number = forms.CharField(max_length=20)
    email = forms.EmailField()
    address = forms.CharField(widget=forms.Textarea)
    department = forms.ModelChoiceField(queryset=Department.objects.all())
    course = forms.ModelChoiceField(queryset=Course.objects.none())
    purpose = forms.ChoiceField(choices=[('Enquiry', 'Enquiry'), ('Order', 'Place Order'), ('Return', 'Return')])
    materials_provide = forms.MultipleChoiceField(
        choices=[('NoteBook', 'Notebook'), ('Textbook', 'Textbook'), ('ExamPapers', 'Exam Papers'),('Stationery','Stationery')],
        widget=forms.CheckboxSelectMultiple()
    )

school_project/school_website/schoolapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
def home(request):
    return render(request,'Home.html')

def register(request):

        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            cpassword = request.POST['password1']

            if password == cpassword:
                if User.objects.filter(username=username).exists():
                    messages.info(request, 'Username already exits')
                    return redirect('schoolapp:register')

                else:
                    user = User.objects.create_user(username=username,password=password)

                    user.save();
                    return redirect('schoolapp:login')
            else:
                messages.info(request, 'password not matched')
                return redirect('schoolapp:register')
            return redirect('/')

        return render(request, "register.html")

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/detail')
        else:

            messages.info(request, 'Invalid Username or Password')
            return redirect('schoolapp:login')

    return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')
def detail(request):
    return render(request,'detail.html')

school_project/school_website/schoolapp1/views.py
from django.shortcuts import render, redirect
from .forms import UserForm

def user_form(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            return redirect('schoolapp1:success')
    else:
        form = UserForm()
    return render(request, 'user_form.html', {'form': form})

def success(request):
    return render(request,'success.html')

school_project/school_website/templates/Home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %}{% endblock %}" >
    <link href="{% static 'css/coustom.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/coustom.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/b247652f0c.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>

    <div class="container">
        <img src="{% static 'img/banner.png' %}" alt="logoimage" width=100%; height="500px">
    </div>
    <div class="container" style="margin-top:10px">
       <img src="{% static 'img/welcome.png' %}" alt="logoimage" width=50%; height="310px">
    </div>
    <div class="container" style="text-align: right; margin-top:10px;">
       <img src="{% static 'img/add.png' %}" alt="logoimage" width=50%; height="310px">
    </div>

  <div class="container" style="margin-top:50px">
    <div class="row">
        <div class="col-lg-3 col-md-4 col-sm-6 col-12">
            <div class="card tm-gallery-item h-100 d-flex">
                <img src="{% static 'img/notebook.jpg' %}" alt="Notebook" class="card-img-top" />
                <div class="card-body text-center" >
                    <h4 class="card-title">Notebook</h4>
                    <p class="card-text">₹100</p>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-4 col-sm-6 col-12">
            <div class="card tm-gallery-item h-100 d-flex">
                <img src="{% static 'img/pencil.jpg' %}" alt="Pencil" class="card-img-top" />
                <div class="card-body text-center">
                    <h4 class="card-title">Pencil</h4>
                    <p class="card-text">₹50</p>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-4 col-sm-6 col-12">
            <div class="card tm-gallery-item h-100 d-flex">
                <img src="{% static 'img/ruler.jpg' %}" alt="Ruler" class="card-img-top" />
                <div class="card-body text-center">
                    <h4 class="card-title">Ruler</h4>
                    <p class="card-text">₹30</p>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-4 col-sm-6 col-12">
            <div class="card tm-gallery-item h-100 d-flex">
                <img src="{% static 'img/pen.jpg' %}" alt="Pen" class="card-img-top" />
                <div class="card-body text-center">
                    <h4 class="card-title">Pen</h4>
                    <p class="card-text">₹60</p>
                </div>
            </div>
        </div>
    </div>
</div>
    <div class="container" style="margin-top:30px">
      <img src="{% static 'img/us.png' %}" alt="logoimage" width=100%; height="200px">
    </div>



    <footer class="tm-footer text-center" style="margin-top:50px">
			<p>Copyright &copy; 2020 Hope School Store
    </footer>
    <script src="{% static 'js/popper.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

school_project/school_website/templates/detail.html
 <style>

    .design2{display:flex;justify-content:center;}
    .button_{display: inline-block;
                    outline: none;
                    cursor: pointer;
                    font-size: 14px;
                    line-height: 1;
                    border-radius: 500px;
                    transition-property: background-color,border-color,color,box-shadow,filter;
                    transition-duration: .3s;
                    border: 1px solid transparent;
                    letter-spacing: 2px;
                    min-width: 160px;
                    text-transform: uppercase;
                    white-space: normal;
                    font-weight: 700;
                    text-align: center;
                    padding: 17px 48px;
                    color: #fff;
                    background-color: #1ED760;
                    height: 48px;
                    margin-top:250px;
                    margin-left:600px;


                    :hover{
                        transform: scale(1.04);
                        background-color: #21e065;
                    }
                }

    </style>

<div >
        <button class="button_" ><a href="{% url 'schoolapp1:user_form' %}">Click here</a></button>
</div>

school_project/school_website/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
     <style>

    .design2{display:flex;justify-content:center;}
    .button_{display: inline-block;
                    outline: none;
                    cursor: pointer;
                    font-size: 10px;
                    line-height: .5;
                    border-radius: 500px;
                    transition-property: background-color,border-color,color,box-shadow,filter;
                    transition-duration: .3s;
                    border: 1px solid transparent;
                    letter-spacing: 2px;
                    min-width: 80px;
                    text-transform: uppercase;
                    white-space: normal;
                    font-weight: 800;
                    text-align: center;
                    padding: 17px 48px;
                    color: #F8F9F9;
                    background-color: #273746;
                    height: 30px;
                    :hover{
                        transform: scale(1.04);
                        background-color: #D1F2EB;
                    }
                }

    </style>

</head>
<body style="background-color:hsla(210, 9%, 70%)">

<div class="design2">

<form action="login" method="post" style="box-sizing:content-box;padding:25px ;box-shadow:50px 20px 80px 80px slategray inset; margin-top:200px; border-radius: 40px;">
    {% csrf_token %}

      <div style="text-align: center;">
  <h3 style="color: white;">LOG IN</h3>
  <input type="text" name="username" placeholder="Username" size="40" style="height: 35px;  border-radius: 500px;"><br><br>
  <input type="password" name="password" placeholder="Password" size="40" style="height: 35px;  border-radius: 500px;"><br><br>
  <button class="button_">Login </button><br><br>
  <a href="{% url 'schoolapp:register' %}" style="text-align: center;">Register Here</a>

 {% if messages %}
<ul style="color: white; list-style-type: none; padding: 0;">
    {% for message in messages %}
        <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

</div>
</form>
</div>


</body>
</html>

school_project/school_website/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href=""  data-bs-toggle="dropdown" aria-expanded="false">
            Department
          </a>

          <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Engineering">ENGINEERING</a></li>
                <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Science">SCIENCE</a></li>
                <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce">COMMERCE</a></li>
                <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Humanities">HUMANITIES</a></li>
                <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Diploma">DIPLOMA</a></li>
          </ul>
         </li>
          </ul>

        <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li> Hello <span>{{user.username}}</span> </li>
                <li class="tm-nav-li"><a href="{% url 'schoolapp:logout' %}" class="tm-nav-link active">Logout</a></li>
            {% else %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'schoolapp:register' %}">Register</a>
        </li>

        <button class="btn btn-outline-success" type="submit"><a href="{% url 'schoolapp:login' %}">Login</a></button>
        {% endif %}

        </ul>


    </div>
  </div>
</nav>

school_project/school_website/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
    <style>
            .design { display:flex;justify-content:center;text-align:left;font-size: medium; padding-bottom:10px;}
            .design1 {font-size: 105% ;font-family:helvetica;color:midnightblue;}
    </style>

</head>
<body>
<form action="{% url 'schoolapp:register' %}" method="post">

<h2 style="text-align :left;font-size:160%;font-family:helvetica;color:midnightblue;">Registration</h2><br>
    {% csrf_token %}
        <label class="design1">Username :</label><br>
        <input type="text" name="username" size="40" style="height:25px;" required placeholder=""><br><br>
        <label class="design1">Password :</label><br>
        <input type="password" name="password" size="40" style="height:25px;"><br><br>
        <label class="design1">Confirm Password :</label><br>
        <input type="password" name="password1" size="40" style="height:25px;"><br><br>
        <input type="submit">

</form>
{% for msg in messages %}
<h3>{{msg}}</h3>
{% endfor %}
</body>
</html>

school_project/school_website/templates/success.html
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  </head>
    <style>
      body {
        text-align: center;
        padding: 40px 0;
        background: #EBF0F5;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>
    <body>
      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
        <h1>Request Confirmed</h1>

        <a href="{% url 'schoolapp:home' %}" class="btn btn-secondary btn-block my_custom_button">HOME</a>
      </div>

    </body>
</html>

school_project/school_website/templates/user_form.html
<!DOCTYPE html>
<html>
<head>
    <title>User Information Form</title>
</head>
<body>
    <h1>User Information Form</h1>
    <form action="{% url 'schoolapp1:success' %}" method="post" onsubmit="return validateForm();">


        {% csrf_token %}
        <label>Name:</label><br>
        {{ form.name }}<br><br>

        <label>DOB:</label><br>
        {{ form.dob }}<br><br>

        <label>Age:</label><br>
        {{ form.age }}<br><br>

        <label>Gender:</label><br>
        {{ form.gender }}<br><br>

        <label>Phone Number:</label><br>
        {{ form.phone_number }}<br><br>

        <label>Email:</label><br>
        {{ form.email }}<br><br>

        <label>Address:</label><br>
        {{ form.address }}<br><br>

       <label for="department">Department:</label><br>
                <select id="department" name="department">
                    <option value="ENGINEERING">B-TECH</option>
                    <option value="SCIENCE">SCIENCE</option>
                    <option value="COMMERCE">COMMERCE</option>
                    <option value="HUMANITIES">HUMANITIES</option>
                    <option value="DIPLOMA">DIPLOMA</option>
                </select><br><br>

        <label for="course">Course:</label><br>
                <select id="course" name="course"></select><br><br>

        <label>Purpose:</label><br>
        {{ form.purpose }}<br><br>

        <label>Materials Provided:</label><br>
        {{ form.materials_provide }}<br>

        <input type="submit" value="Submit">

        <button type="button" onclick="window.location.href = '{% url 'schoolapp:home' %}';">Logout</button>
    </form>

<script>
    // Define department and course data
    const departmentCourses = {
        'ENGINEERING': ['ECE', 'CSE', 'EEE'],
        'SCIENCE': ['BSc Physics', 'BSc Chemistry', 'BSc Mathematics'],
        'COMMERCE': ['BCom', 'BBA', 'BCA'],
        'HUMANITIES': ['Sociology', 'History', 'Geography'],
        'DIPLOMA': ['Fashion design', 'Psychology', 'Textile engineering'],
    };

    // Function to update the courses dropdown
    function updateCoursesDropdown() {
        const departmentDropdown = document.getElementById('department');
        const courseDropdown = document.getElementById('course');
        const selectedDepartment = departmentDropdown.value;

        // Clear the courses dropdown
        courseDropdown.innerHTML = '<option value="">Select Department First</option>';

        // Populate the courses dropdown based on the selected department
        if (selectedDepartment in departmentCourses) {
            const courses = departmentCourses[selectedDepartment];
            courses.forEach(course => {
                const option = document.createElement('option');
                option.value = course;
                option.text = course;
                courseDropdown.appendChild(option);
            });
        }
    }

    // Event listener to update courses dropdown when department changes
    const departmentDropdown = document.getElementById('department');
    departmentDropdown.addEventListener('change', updateCoursesDropdown);

    // Initial update of the courses dropdown
    updateCoursesDropdown();

    function calculateAge() {
        // Get the value of the DOB field
        const dobField = document.getElementById('id_dob');
        const dobValue = dobField.value;

        // Check if dobValue is not empty and matches the 'YYYY-MM-DD' format
        if (dobValue && dobValue.match(/^\d{4}-\d{2}-\d{2}$/)) {
            const dobDate = new Date(dobValue);
            const today = new Date();
            const age = today.getFullYear() - dobDate.getFullYear();

            // Set the calculated age in the age field
            const ageField = document.getElementById('age-field');
            ageField.value = age;
        }
    }

    // Attach the calculateAge function to the change event of the DOB field
    const dobField = document.getElementById('id_dob');
    dobField.addEventListener('change', calculateAge);

    // Initial calculation of age when the page loads
    calculateAge();

     // Function to validate the form
        function validateForm() {
            // Check if any required fields are empty
            const nameField = document.getElementById('id_name');
            const dobField = document.getElementById('id_dob');
            const genderField = document.getElementById('id_gender');
            const phoneNumberField = document.getElementById('id_phone_number');
            const emailField = document.getElementById('id_email');
            const addressField = document.getElementById('id_address');

            if (
                nameField.value === "" ||
                dobField.value === "" ||
                genderField.value === "" ||
                phoneNumberField.value === "" ||
                emailField.value === "" ||
                addressField.value === ""
            ) {
                alert("Please fill in all required fields.");
                return false; // Prevent form submission
            }

            // Additional validation if needed

            return true; // Allow form submission if all checks pass
        }
</script>

</body>
</html>